# Generated by Django 4.2 on 2023-04-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customersData',
            new_name='customers_Data',
        ),
    ]
