# Generated by Django 4.2 on 2023-04-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankSystem', '0002_rename_customersdata_customers_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_data',
            name='sNum',
        ),
    ]
