# Generated by Django 4.2 on 2023-04-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankSystem', '0003_remove_customers_data_snum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccountNumber', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
